### ISSUE TITLE
Wind direction seems too stable - no rotation?

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#13] opened 2022-11-20 16:27 UTC
```python
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("Roof_GEUS_hour.csv", parse_dates=True, index_col=0)
df = df['2022-11-09':'2022-11-11']
df[['z_boom_u','z_boom_u']].plot()
df[['wdir_l','rot']].plot()
```

The above code produces the following graphic
![Screenshot_2022-11-20_082838](https://user-images.githubusercontent.com/145117/202913707-f07e274e-d62f-4357-b04e-7f6811360bb8.png)

It looks like there are two issues here, but I don't see a rotation label.

First, the direction seems too stable. When I plot the `wdir_u`, there is variability.

Second, unrelated, it appears the station was rotated by ~50ish degrees.

**Comment by mankoff** [comment] 2022-11-20 16:38
Might be related to this tape stopping rotation of the wind vane.

![PXL_20221109_115641580](https://user-images.githubusercontent.com/145117/202914221-c29267f4-7b0f-455e-8437-c8ec7cb484f2.jpg)

**Comment by patrickjwright** [comment] 2022-11-23 12:10
Interesting.... :)

However, looking out the window (the best way to confirm anything) I do not see any tape!
I can confirm in the data, but guessing this is likely resolved.

**Comment by mankoff** [comment] 2022-11-23 15:05
Tape resolved, but this ticket is open to handle addressing the invalid data.

**Comment by mankoff** [comment] 2022-11-23 15:59
I'm not sure where flagging takes place at the moment. Looks like it might not be in the repository. I think the idea was to move the CSV to the data repository, not the code repository (it's metadata, a.k.a data, not code). Anyway, in this old commit of pypromice https://github.com/GEUS-Glaciology-and-Climate/pypromice/tree/b1aec6fc50364d2a8da89d3ba5a400f70faaf1ff there is a flags.org document https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/b1aec6fc50364d2a8da89d3ba5a400f70faaf1ff/flags.org and a flags.csv file https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/b1aec6fc50364d2a8da89d3ba5a400f70faaf1ff/flags.csv

It should be straightforward to zero-out the invalid data from all these open issues. It is more complicated to fix the data (when and where it can be fixed) but @BaptisteVandecrux has a template for that.

**Comment by BaptisteVandecrux** [comment] 2022-11-24 09:14
I have created a branch where data flagging is re-enabled.

Here is the function that does it:
https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/c159955e4c5b4392cd62e82c908cbce165735b0b/src/pypromice/L0toL1.py#L122-L163

I have placed a first draft of csv file for Roof_GEUS here:
https://github.com/GEUS-Glaciology-and-Climate/pypromice/tree/data-flagging/src/pypromice/data/flags

I do not have the L0 data on my machine so cannot test it atm.
Of course it's open to discussion whether that's the way we want to do it. 

Note that in Ken's template we considered putting all flags for all stations, but it is much clearer to have one file per station.

**Comment by patrickjwright** [comment] 2022-11-24 10:04
@mankoff @BaptisteVandecrux I can check out Baptiste's approach and test it. From a database perspective, it makes sense to have all flags for all stations in one place, with another column for station ID. But from a usability standpoint (and because we are not actually using a database for flagging) then perhaps it makes more sense to have station specific .csv files. Organizationally it might be easier to open up a file just for a single station to manually add another flagged range.

As we move forward, it would be nice to have an arg in the processing to enable/disable certain flags or groups of flags (using flag IDs). As we develop more automated QC tests, we can have some flags (such as the existing "range" flag) that almost all users will always want to enable. However, we may have additional flags that could be more aggressive than some users desire, and they could be toggled off. So, I might have a look at @BaptisteVandecrux 's suggested flag file and suggest additional fields in the header.

Setting flagged data to NaN for now seems fine.

I also agree that we should examine whether this lives in pypromice or AWS-L0 repo.

Hoping to have time to dig in on this further soon.

**Comment by BaptisteVandecrux** [comment] 2023-02-07 14:52
![image](https://user-images.githubusercontent.com/35140661/217491428-e9caf2f8-b480-42ad-be92-37284bbcb723.png)

Both wind direction and wind speed are flagged as erroneous and removed from the L2 and L3 data in the upcoming release.

Yet Roof_GEUS is an experimental station, undergoes a lot of modification/manipulation and should not be considered as reliable.

**Comment by BaptisteVandecrux** [comment] 2023-05-25 08:11
We now have the framework to flag or correct data within pypromice. Closing this.

**Closed as completed by BaptisteVandecrux** 2023-05-25 08:11 UTC
Labels: WindDirection, 2022, Roof_GEUS, fixed in future release
